apiVersion: v1
kind: Namespace
metadata:
  name: buildkite-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buildkite-metrics:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: buildkite-metrics-apiserver
  namespace: buildkite-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildkite-metrics-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: buildkite-metrics-apiserver
  namespace: buildkite-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkite-metrics-apiserver
  name: buildkite-metrics-apiserver
  namespace: buildkite-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkite-metrics-apiserver
  template:
    metadata:
      labels:
        app: buildkite-metrics-apiserver
      name: buildkite-metrics-apiserver
    spec:
      serviceAccountName: buildkite-metrics-apiserver
      containers:
      - name: buildkite-metrics-apiserver
        image: buildkite-agent-metrics-adapter:take8
        imagePullPolicy: IfNotPresent
        args:
        - /adapter
        - --logtostderr=true
        - --buildkite-agent-token
        - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        #- --v=10
        ports:
        - containerPort: 443
          name: https
        volumeMounts:
        - mountPath: /tmp
          name: temp-vol
      volumes:
      - name: temp-vol
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buildkite-metrics-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: buildkite-metrics-resource-reader
subjects:
- kind: ServiceAccount
  name: buildkite-metrics-apiserver
  namespace: buildkite-metrics
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: buildkite-metrics-apiserver
  namespace: buildkite-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: buildkite-metrics-apiserver
  namespace: buildkite-metrics
spec:
  ports:
  - name: https
    port: 443
  selector:
    app: buildkite-metrics-apiserver
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: buildkite-metrics-apiserver
    namespace: buildkite-metrics
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: buildkite-metrics-server-resources
#rules:
#- apiGroups:
#  - custom.metrics.k8s.io
#  resources: ["*"]
#  verbs: ["*"]
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: buildkite-metrics-resource-reader
#rules:
#- apiGroups:
#  - ""
#  resources:
#  - namespaces
#  - pods
#  - services
#  verbs:
#  - get
#  - list
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: hpa-controller-buildkite-metrics
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: buildkite-metrics-server-resources
#subjects:
#- kind: ServiceAccount
#  name: horizontal-pod-autoscaler
#  namespace: kube-system